services:
  tak-situational-backend:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.backend
    image: tak-situational-backend:latest
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    restart: always
    container_name: tak-situational-backend
  tak-situational-frontend:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.frontend
    image: tak-situational-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://tak-situational-backend:8000
    depends_on:
      - tak-situational-backend
    restart: always
    container_name: tak-situational-frontend
